### ISSUE TITLE
Confusing and_then usage in docs

### ISSUE THREAD

**Issue by caspark** [carllerche/eventual#10]
In [the docs](http://carllerche.github.io/eventual/eventual/index.html), there's this snippet:

```
let res = join((
        future1.map(|v| v * 2),
        future2.map(|v| v + 5)))
    .and_then(|(v1, v2)| v1 - v2)
    .await().unwrap();
```

That's somewhat confusing to me because `and_then` appears to be the same as `map`; I was expecting something like `.and_then(|(v1, v2)| Ok(v1 - v2))` which works as expected and is more in line with the `and_then`s in the standard library (and the `flatmap` in Scala/Scalaz's futures, which I'm most familiar with).

Anyway, I'm happy to raise a PR to correct the docs, but I have a possibly stupid question on the topic as well: how is it that both versions actually compile & work correctly? From `Async.and_then()` defined in `lib.rs`, I see

```
fn and_then<F, U: Async<Error=Self::Error>>(self, f: F) -> Future<U::Value, Self::Error>
            where F: FnOnce(Self::Value) -> U + Send,
                  U::Value: Send {
```

so U must be an Async, which explains how `Ok(v1 - v2)` works.. but how does `v1 - v2` get "implicitly converted" to an `Async` when there is no `Ok()`? With the exception of automatic dereferencing, I haven't seen that kind of implicit conversion behaviour in Rust before.

**Comment by reem** [comment]
There is this set of concrete impls https://github.com/carllerche/eventual/blob/master/src/lib.rs#L370-L373, which allows this to work without the `Ok`.

**Comment by carllerche** [comment]
@caspark You are correct that the example is confusing. `and_then(...)` and `map(...)` are very similar. I debated whether having both of them (since `map` is a subset of `and_then(...)` but ended up keeping both because `std::result::Result` has both.

I'm unsure if the best strategy is to change the docs to simply change `Ok(v1 - v2)` for explicitness or to change the example more to use a type that doesn't implement `Async` directly (as pointed out by @reem above).

**Comment by caspark** [comment]
Thanks @reem - I looked for something like that and I remember seeing the macro definition but not the macro call.

@carllerche Both changing the docs and using a type that does not implement Async would be the clearest.

Going further, in my opinion, it would be better to not provide implementations of Async for types*; doesn't that just encourage users of the library to make mistakes by encouraging them to implement Async for their own types? And it's nice to have a level playing field for std types and custom types from the get go.

(\* it looks like a missing Async impl for `()` causes tests to fail and I don't know this library well enough to judge whether that's reasonable or not, but the impls for other primitives don't appear to be necessary aside from the case in the docs I've already called out.)

Considering it from another angle, in my mind there is a very clear delineation between `map` & `and_then` (carried over from Scala's `map` & `flatmap`, which are approximately equivalent): when I see the `map` in code, then I know that - aside from panics - it isn't going to cause a failure (in a `Future`), error (in a `Result`), or throw away information (in an `Option`). So I believe making it easier for people to use `and_then` when they really mean `map` is not a good thing, because `and_then` sets certain expectations for the reader.

Of course, I might well be missing why it's a really good idea to implement Async directly for types - I've only just started playing around with this library :)

**Comment by carllerche** [comment]
Well, there is a reason to implement `()` as a special case given that void fn returns actually return `()` (and i was experimenting with some various things that needed to use this face).

However, the other implementations are not strictly necessary. I added them because one day w/ specialization it would be possible to do this for all types (aka, have a default implementation of `Async` that returns `self` immediately).

Anyway, I would be open to considering removing all implementations `Async` for the rust core types except for `()`.

**Comment by caspark** [comment]
Alright, I'll put a PR together for it then.
