### ISSUE TITLE
[Suggestion] Automatic timeout

### ISSUE THREAD

**Issue by Anachron** [carllerche/eventual#2]
Is it possible to add a timeout for futures?
This would make future-code easier to maintain.

**Comment by carllerche** [comment]
Could you say more? I plan on adding a timeout variant to `Async::await()` which blocks. However, that's the only timeout that I can have built in since Eventual doesn't have any concept of scheduling. Libraries using Eventual could provide timeouts though. There could be a library that provides timeout futures, so you can do:

``` rust
let timeout = timeout_lib::timeout_ms(200);
let future = some_action();

eventual::select((future, timeout))
  .and_then(|_| {
    // Do something
  });
```

**Comment by Anachron** [comment]
Basically it's a async timeout that will be triggered after a while to automatically reject a promise (future) after a given amount of time. It shouldn't delay any of the other actions during that time.

**Comment by Anachron** [comment]
To automatically reject if it has not been rejected or solved yet*

So on reject or solve the timer should be stopped/destroyed.

**Comment by carllerche** [comment]
This is resolved by: https://github.com/carllerche/eventual/blob/master/src/timer.rs
