### ISSUE TITLE
Future::spawn that can return an error?

### ISSUE THREAD

**Issue by bholt** [carllerche/eventual#36]
I'm stuck on what seems to be a really simple task: I'd like a Future to go off and run something, like `spawn` does, but if something goes wrong during the execution of that Future, it should return an error. However, it looks to me like `spawn` requires success. On the other hand, there's the `lazy` Future creator which _does_ allow returning errors, but doesn't start doing work until later (presumably so its work can be done on the waiting thread rather than spawning a new thread?)

Is there a way to create a Future that runs immediately like `spawn` but allows an error to be returned?

Sorry, I'm very new to Rust and am trying to port a library using the now-deprecated `std::sync::Future`s (aside: where did those go, are they available in a crate that I can't seem to find?)  and @jroesch suggested that this crate is probably my best choice for futures.

Thanks!

**Comment by TyOverby** [comment]
I can't say for certain why `spawn` doesn't support failure, but you can write your own spawn function fairly easily!

``` rust

extern crate eventual;

use eventual::Future;
use std::thread;

fn spawn<T, E, F>(f: F) -> Future<T, E>
where F: FnOnce() -> Result<T, E> + Send + 'static,
      T: Send + 'static,
      E: Send + 'static
{
    let (completer, future) = Future::pair();
    thread::spawn(move || match f() {
        Ok(good) => completer.complete(good),
        Err(bad) => completer.fail(bad)
    });

    future
}
```

**Comment by bholt** [comment]
Thanks! That's straightforward enough, and working for me so far. :)

**Comment by carllerche** [comment]
I see that this was resolved for you. Sorry for the delay.

`Future::spawn` mostly exists as a mirror for the API that existed in [`std::sync::Future`](https://doc.rust-lang.org/stable/std/sync/struct.Future.html#method.spawn). Personally, I don't find an API that spawns a thread by default super useful, but as pointed out, it's not much code :)

In general, this confusion is also due to a lack of docs. Unfortunately, I'm pretty busy w/ real work + trying to get mio to 1.0...
